monolog:
  handlers:
    # ...
    console:
      type:   console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine', '!console']

      # optionally configure the mapping between verbosity levels and log levels
      verbosity_levels:
        VERBOSITY_NORMAL: debug